package test.model;

import javax.persistence.*;

@Table(name = "`country`")
public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countryname
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    private String countryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.countrycode
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    private String countrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.version
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countryname
     *
     * @return the value of country.countryname
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countryname
     *
     * @param countryname the value for country.countryname
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.countrycode
     *
     * @return the value of country.countrycode
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.countrycode
     *
     * @param countrycode the value for country.countrycode
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.version
     *
     * @return the value of country.version
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.version
     *
     * @param version the value for country.version
     *
     * @mbg.generated Wed Oct 31 11:04:11 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}